spring:
  application:
    name: config-server
  
  cloud:
    config:
      server:
        git:
          ur: https://github.com/192.168.72.131/config
          searchPaths: config
          username: root
          password: root
    
server:
  port: 6001
   
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        